### PR TITLE
Expanded documentation, heavily inspired by the discourse tutorials

### PR DESCRIPTION
**Pull request by casparvl**
Since I've just gone through a first-time setup of creating a Vantage6 infrastructure (server, two nodes, a collaboration, two organizationas, a few end-users, etc), I hit quite some issues that I had difficulty figuring out based on the official documentation.

The discourse tutorials helped, but both myself and two colleagues didn't find these initially (I was pointed to it by an external collaborator). I think it would really help if the key points from the tutorials where integrated with the official documentation. This makes it a) easier to find and b) allows others to contribute to it (e.g. [this tutorial](https://vantage6.discourse.group/t/7-running-an-algorithm/41) seems to miss a step in defining the `result_id`: it is used, but never defined. If it were under version control, I could do a PR to add to it :)).

Note that this documentation update is heavily inspired by the discourse tutorials (credit where credit is due, of course!), but I've tried to structure it more in a user-manual style, rather than a tutorial. Also, I elaborate a bit more on the differences between RPC & master tasks, since that wasn't fully clear to me from the tutorial (so please double check that I got this part correctly :)).

Anyway, I hope you are open to this contribution!

On a side node: if you would be open to more contributions to the documentation, I would also like to try to find the time to write a tutorial that focusses more on the administrative part (no promisses though, I might not be able to find the time :)). There's quite a particular order to things if you want to setup a new V6 infrastructure (e.g. start with a V6 server, create an initial login or use the default one so that you can connect a client, create a keypair for the organization(s), create organization(s), create collaboration(s), use the client to register a node, then create a node with `vnode new` and use the `api_key` you got from registering the node and the path to private key from the keypair, ...). This order is not always intuitive. E.g. based on the current official docs, I followed the installation steps for both the V6 server and node, then configured the V6 server, and then started to configure a new node with `vnode new` - but this was even before I had an `api_key` or keypair (and then wondered what to fill in here when the wizard prompted me for those...). I think a tutorial that orders these steps, and then references the relevant parts of the documentation (e.g. registering a node would be a step that is explained already in the docs of this PR) can make this process a lot easier for people who are new to managing Vantage6 infrastructure.

### CODE REVIEW

**Comment by bartvanb** [comment]
Hi Caspar, great that you're taking the initiative to improve the documentation! I unfortunately don't have time now but will make sure to review it next week.

We are struggling a bit with how and where to best document the different parts of Vantage6 and your feedback is very useful. Our general idea when writing this documentation was to limit the scope to introducing the infrastructure and describe the set up process, so we put the more extended tutorials somewhere else (in Discourse) by design. However, as you indicate, with the current docs it is difficult to set up a vantage6 environment (server, nodes, users etc). I do agree that one should be able to set this up using the documentation.

A small note on Discourse: indeed the existence of these pages are not advertised in many places at this time. This is mainly because we are not (yet) very satisfied with these pages and are considering if we should bring them to the next level or migrate to some other form.

In case you do find the time to write an administrative tutorial on how to set up vantage6 from scratch, this would be very welcome! I am not sure that this documentation is the best place for such a tutorial (might be, might not be). We should then discuss where we could put it to maximize its usefulness.

**Comment by bartvanb** [comment]
Just merged this. Thanks again @casparvl for the very useful contribution! I went over the text and might still make a few tiny changes but it looks excellent.

This is the first time we have updated the docs from this git repository: usually we work directly in Gitbook. We set it up to sync both ways to it should be updated automatically. At this moment, however, I don't see the changes yet in the docs. I will keep an eye on this.

**Comment by bartvanb** [comment]
Ah, I just found out why it doesn't sync: we are making these changes in the old repository. Recently, we moved this repository into the 'Vantage6' organization: https://github.com/vantage6/gitbook-docs. @casparvl could you be so kind to re-create this pull request in that repository?
I will also make sure to archive this old repository afterward.

FYI we will be moving some more repositories from the IKNL organization to the Vantage6 organization later this year, mainly to give proper credit as Vantage6 is not only developed by IKNL employees.

**Comment by casparvl** [comment]
It took me a bit of fiddling, but I think I managed. See https://github.com/vantage6/gitbook-docs/pull/1

**Pull request merged**
